---
# note: we use copy here just so we can run through to_nice_json
- name: Generate Kraken state file
  copy:
    content: "{{ lookup('template', 'nodes.json.j2') | to_nice_json }}"
    dest: "{{ kraken_state_file }}"
    mode: 0644
  notify: kraken inject state
