---
- hosts: kraken
  connection: local
  tasks:
    - name: "Template state file"
      copy:
        content: >
          {{
            lookup('template', 'roles/kraken-state/templates/nodes.json.j2') |
            to_nice_json
          }}
        dest: "kraken-state.json"
